# Generated by Django 5.1.5 on 2025-01-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="money",
            field=models.IntegerField(default=0),
        ),
    ]
