# Generated by Django 5.1.5 on 2025-01-30 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_customer_money"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="old_value",
            new_name="total",
        ),
        migrations.AddField(
            model_name="wallet",
            name="transaction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
