# Generated by Django 5.1.5 on 2025-01-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_rename_old_value_wallet_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="package",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.package",
            ),
        ),
    ]
