# Generated by Django 5.1.5 on 2025-02-13 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameField(
            model_name="history",
            old_name="input_data",
            new_name="input_text",
        ),
        migrations.RemoveField(
            model_name="history",
            name="date",
        ),
        migrations.RemoveField(
            model_name="history",
            name="output_data",
        ),
        migrations.AddField(
            model_name="history",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.package",
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="history",
            name="voice_file",
            field=models.FileField(blank=True, null=True, upload_to="tts_outputs/"),
        ),
        migrations.AlterField(
            model_name="history",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["timestamp"], name="home_histor_timesta_9bfceb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["customer"], name="home_histor_custome_a78294_idx"
            ),
        ),
    ]
