# Generated by Django 5.1.5 on 2025-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_history_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="text_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
