# Generated by Django 5.1.5 on 2025-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_history_text_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="input_text",
        ),
        migrations.RemoveField(
            model_name="history",
            name="text_file",
        ),
        migrations.RemoveField(
            model_name="history",
            name="voice_file",
        ),
        migrations.AddField(
            model_name="history",
            name="character_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="history",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="text_preview",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["package"], name="home_histor_package_dee8a5_idx"
            ),
        ),
    ]
